// Generated by https://quicktype.io

export interface PlacesResponse {
  type: string;
  query: string[];
  features: Feature[];
  attribution: string;
}

export interface Feature {
  id: string;
  type: string;
  place_type: string[];
  relevance: number;
  properties: Properties;
  text_de: string;
  place_name_de: string;
  text: string;
  place_name: string;
  text_en: string;
  place_name_en: string;
  text_es: string;
  place_name_es: string;
  center: number[];
  geometry: Geometry;
  context: { [key: string]: string }[];
}

export interface Geometry {
  type: string;
  coordinates: number[];
}

export interface Properties {
  accuracy: string;
}
